title = "Notre-Dame de Paris"
baseURL = "https://davokr.github.io/ProbablyTroy.com/"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false

[languages]
  [languages.en]
    title = "My blog"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 0

#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/GoHugoIO"

[markup.goldmark.renderer]
unsafe = true